[build-system]
requires = [ "setuptools>=41", "wheel", "setuptools-git-versioning<2", ]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "wow-test-project"
description = "wow test project"
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"eot.test" = ["*.txt", "*.rst"]

[tool.setuptools-git-versioning]
enabled = true
template = "{tag}"
#dev_template = "{tag}.dev{ccount}"
#tag_formatter = "util:format_tag_name"
